name: Build EXE with PyInstaller

on:
  push:
    branches:
      - main
    paths:
      - '**.py'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build EXE
      run: |
        pyinstaller --onefile --noconsole pdf_checker.py

    - name: Upload EXE as artifact
      uses: actions/upload-artifact@v3
      with:
        name: pdf_checker_exe
        path: dist/pdf_checker.exe
